# Generated by Django 3.0.5 on 2021-05-10 17:07

import crud.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=70)),
                ('mapExtent', djongo.models.fields.EmbeddedField(model_container=crud.models.MapExtent)),
                ('boundary', djongo.models.fields.EmbeddedField(model_container=crud.models.Boundary, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='LocationSets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systemInformation', djongo.models.fields.EmbeddedField(model_container=crud.models.SystemInformation)),
                ('datetime', djongo.models.fields.EmbeddedField(model_container=crud.models.DatetimeDefinition)),
                ('map', djongo.models.fields.EmbeddedField(model_container=crud.models.Map, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Timeseries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
                ('description', models.CharField(default='', max_length=100)),
                ('unit', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
