# Generated by Django 3.0.5 on 2021-06-03 14:51

import crud.models
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boundary',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('geoDatum', models.CharField(default='WGS 1984', max_length=10)),
                ('projection', models.CharField(default='web_mercator', max_length=50)),
                ('polygon', djongo.models.fields.JSONField()),
                ('linecolor', models.CharField(default='#333333', max_length=10)),
                ('lineWidth', models.IntegerField(default=1)),
                ('fillcolor', models.CharField(default='', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DatetimeDefinition',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('timezone', models.CharField(default='UTC', max_length=3)),
                ('datetimeFormat', models.CharField(default='YYYY-MM-DD HH:mm', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.CharField(default='', max_length=100)),
                ('mapExtent', djongo.models.fields.EmbeddedField(model_container=crud.models.MapExtent)),
                ('boundary', djongo.models.fields.EmbeddedField(model_container=crud.models.Boundary, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=70)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LocationSets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('geoDatum', models.CharField(default='WGS 1984', max_length=10, null=True)),
                ('projection', models.CharField(default='web_mercator', max_length=50, null=True)),
                ('defaultExtent', djongo.models.fields.EmbeddedField(model_container=crud.models.MapExtent, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MapExtent',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70, null=True)),
                ('top', models.FloatField(default=180.0)),
                ('bottom', models.FloatField(default=-180.0)),
                ('left', models.FloatField(default=-180.0)),
                ('right', models.FloatField(default=180.0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systemInformation', djongo.models.fields.EmbeddedField(model_container=crud.models.SystemInformation)),
                ('datetime', djongo.models.fields.EmbeddedField(model_container=crud.models.DatetimeDefinition)),
                ('map', djongo.models.fields.EmbeddedField(model_container=crud.models.Map, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemInformation',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('name', models.CharField(default='DEFAULT TITLE', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimeseriesEvent',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('date', models.CharField(default='YYYY-MM-DD', max_length=10)),
                ('time', models.CharField(default='00:00:00', max_length=8)),
                ('value', models.FloatField()),
                ('flag', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TimeseriesTimestep',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('unit', models.CharField(default='nonequidistant', max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Timeseries',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('header_units', models.CharField(default='', max_length=10)),
                ('header_missVal', models.FloatField()),
                ('header_type', models.CharField(default='', max_length=20)),
                ('header_parameterId', models.CharField(default='', max_length=20)),
                ('header_stationName', models.CharField(default='', max_length=20)),
                ('header_timeStep_unit', models.CharField(default='', max_length=10)),
                ('events', djongo.models.fields.ArrayField(model_container=crud.models.TimeseriesEvent)),
                ('filter_set', djongo.models.fields.ArrayReferenceField(on_delete=django.db.models.deletion.DO_NOTHING, to='crud.Filter')),
                ('header_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crud.Location')),
            ],
        ),
        migrations.AddField(
            model_name='filter',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='crud.Location'),
        ),
    ]
