# Generated by Django 3.0.5 on 2021-05-11 14:00

import crud.models
from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boundary',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('geoDatum', models.CharField(default='WGS 1984', max_length=10)),
                ('projection', models.CharField(default='web_mercator', max_length=50)),
                ('polygon', djongo.models.fields.JSONField()),
                ('linecolor', models.CharField(default='#333333', max_length=10)),
                ('lineWidth', models.IntegerField(default=1)),
                ('fillcolor', models.CharField(default='', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DatetimeDefinition',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('timezone', models.CharField(default='UTC', max_length=3)),
                ('datetimeFormat', models.CharField(default='YYYY-MM-DD HH:mm', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('geoDatum', models.CharField(default='WGS 1984', max_length=10, null=True)),
                ('projection', models.CharField(default='web_mercator', max_length=50, null=True)),
                ('defaultExtent', djongo.models.fields.EmbeddedField(model_container=crud.models.MapExtent, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MapExtent',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=70, null=True)),
                ('top', models.FloatField(default=180.0)),
                ('bottom', models.FloatField(default=-180.0)),
                ('left', models.FloatField(default=-180.0)),
                ('right', models.FloatField(default=180.0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SystemInformation',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('name', models.CharField(default='DEFAULT TITLE', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
