# Generated by Django 3.0.5 on 2021-05-11 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_boundary_datetimedefinition_map_mapextent_systeminformation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Boundary',
        ),
        migrations.DeleteModel(
            name='DatetimeDefinition',
        ),
        migrations.DeleteModel(
            name='Map',
        ),
        migrations.DeleteModel(
            name='MapExtent',
        ),
        migrations.DeleteModel(
            name='SystemInformation',
        ),
    ]
